# Crypto Narrative Pulse Tracker - RAG Configuration
# Built on Pathway RAG template for real-time crypto sentiment analysis
# https://pathway.com/developers/templates/configure-yaml

# =============================================================================
# DATA SOURCES
# =============================================================================
# Primary: HTTP webhook for messages from simulator/external sources
# Secondary: File system for static documents

$sources:
  # HTTP webhook connector for real-time message ingestion
  # Messages from Hype Simulator and external webhooks arrive here
  - !pw.io.http.rest_connector
    host: "0.0.0.0"
    port: 8080
    schema: !pw.Schema
      message_id: str
      text: str
      author_id: str
      author_followers: int
      timestamp: str
      tags: list
      engagement_count: int
      source_platform: str
    delete_completed_queries: false

  # File System connector for static crypto documents/research
  - !pw.io.fs.read
    path: data
    format: binary
    with_metadata: true



# =============================================================================
# LLM CONFIGURATION
# =============================================================================
# Using Ollama for local LLM inference (no API costs)

$llm_model: "ollama/mistral"

$llm: !pw.xpacks.llm.llms.LiteLLMChat
  model: $llm_model
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
  cache_strategy: !pw.udfs.DefaultCache {}
  temperature: 0.1
  api_base: "http://ollama:11434"  # Docker service name
  # api_base: "http://localhost:11434"  # Use for local development
  async_mode: "fully_async"

# =============================================================================
# EMBEDDING CONFIGURATION
# =============================================================================
$embedding_model: "avsolatorio/GIST-small-Embedding-v0"

$embedder: !pw.xpacks.llm.embedders.SentenceTransformerEmbedder
  model: $embedding_model
  call_kwargs:
    show_progress_bar: False

# =============================================================================
# DOCUMENT PROCESSING
# =============================================================================
# Splitter for chunking documents
$splitter: !pw.xpacks.llm.splitters.TokenCountSplitter
  max_tokens: 400

# Parser for processing documents
$parser: !pw.xpacks.llm.parsers.DoclingParser
  table_parsing_strategy: "llm"
  async_mode: "fully_async"
  chunk: false
  cache_strategy: !pw.udfs.DefaultCache {}

# =============================================================================
# RETRIEVER AND DOCUMENT STORE
# =============================================================================
# Retriever factory for indexing and retrieving documents
$retriever_factory: !pw.indexing.UsearchKnnFactory
  reserved_space: 2000  # Increased for crypto message volume
  embedder: $embedder
  metric: !pw.indexing.USearchMetricKind.COS

# Document store for RAG - indexes messages with metadata
# Configured to index crypto messages with sentiment, influence_score, source_platform
# Requirements: 8.1, 8.2
$document_store: !pw.xpacks.llm.document_store.DocumentStore
  docs: $sources
  parser: $parser
  splitter: $splitter
  retriever_factory: $retriever_factory

# =============================================================================
# CRYPTO MESSAGE INDEXING CONFIGURATION
# =============================================================================
# Metadata fields to index with each message (Requirements: 8.2)
# - message_id: Unique identifier for the message
# - timestamp: When the message was created
# - sentiment: Sentiment score from -1 to 1
# - influence_score: Author influence (followers * 0.6 + engagement * 0.4)
# - source_platform: Origin platform (simulator, twitter, discord)
crypto_metadata_fields:
  - message_id
  - timestamp
  - sentiment
  - influence_score
  - source_platform
  - author_id
  - author_followers
  - engagement_count
  - tags

# RAG retrieval configuration (Requirements: 8.3)
rag_top_k: 15  # Retrieve top 15 most relevant messages

# =============================================================================
# QUESTION ANSWERING (RAG)
# =============================================================================
# Crypto-optimized RAG question answerer
# Uses AdaptiveRAG for better context retrieval (Requirements: 8.3, 8.4)
question_answerer: !pw.xpacks.llm.question_answering.AdaptiveRAGQuestionAnswerer
  llm: $llm
  indexer: $document_store
  n_starting_documents: 5  # Start with more docs for crypto context
  factor: 2
  max_iterations: 4
  strict_prompt: true

# =============================================================================
# CRYPTO RAG PROMPT TEMPLATE
# =============================================================================
# Custom prompt template for crypto-specific RAG queries
# Enriched with live metrics: pulse_score, trending_phrases, influencer_consensus
# Requirements: 8.4
crypto_rag_prompt_template: |
  You are a crypto momentum analyst. Answer based on LIVE social data.

  Current Pulse Score: {pulse_score}/10
  Top Trending Phrases: {trending_phrases}
  Influencer Consensus: {influencer_consensus}
  Price-Sentiment Status: {divergence_status}

  Recent messages:
  {context}

  User question: {query}

  Provide:
  1. Direct answer with pulse score interpretation
  2. Top 3 repeating phrases from recent threads
  3. Risk assessment (are we early or late to this narrative?)

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
host: "0.0.0.0"
port: 8000

# =============================================================================
# PERSISTENCE CONFIGURATION
# =============================================================================
# Enable persistence for fault tolerance (survives container restarts)
persistence_mode: !pw.PersistenceMode.PERSISTING
persistence_backend: !pw.persistence.Backend.filesystem
  path: "./Cache"

# Set to true to terminate on errors (useful for debugging)
terminate_on_error: false

# =============================================================================
# CRYPTO PULSE TRACKER CUSTOM SETTINGS
# =============================================================================
# These settings are used by the crypto pulse tracker components

# Temporal window configuration (5-min sliding, 1-min hop)
window_duration_mins: 5
window_hop_mins: 1

# Sentiment thresholds
strong_bullish_threshold: 0.7
strong_bearish_threshold: -0.7

# Influencer classification threshold
influencer_score_threshold: 10000

# Trending phrase minimum frequency
trending_phrase_min_frequency: 5

# Alert thresholds
alert_high_score: 7
alert_low_score: 3

# Divergence detection thresholds
divergence_sentiment_threshold: 0.5
divergence_price_threshold: 2.0
